version: '3.9'
services:
  web:
    image: 
    container_name: ${WEB_CONT_NAME}
    build: frederikotto/riv4lz-frontend:${IMAGE_TAG}
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${WEB_PORT}:80
    